# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-21 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paulscabins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='picture',
            field=models.ImageField(default='tradehouse/default.jpg', upload_to='tradehouse'),
        ),
    ]
