# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-21 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paulscabins', '0002_testimonial_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='picture',
            field=models.ImageField(default='cabinuploads/default.jpg', upload_to='cabinuploads'),
        ),
    ]
