# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-22 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paulscabins', '0003_auto_20180721_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('picture', models.ImageField(default='ronsuploads/default.jpg', upload_to='ronsuploads')),
            ],
        ),
    ]
